name: Build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm'
      - run: ./gradlew build
      - run: ./gradlew nativeCompile
      - run: | 
          ls -al build 
          ls -al build/native 
          ls -al build/native/nativeCompile
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/eroshenkoam/allure-testops-utils:native
