name: Build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.x
      - name: "Build Project"
        run: ./gradlew build prepareDockerfile
      - name: Build Docker
        uses: docker/build-push-action@v2
        with:
          push: false
          context: build/docker
          tags: ghcr.io/eroshenkoam/allure-testops-utils
