name: Build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-20.04	
    steps:
      - uses: actions/checkout@v1
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm'
      - run: ./gradlew build
      - run: ./gradlew nativeCompile
      - run: ./gradlew prepareDockerfile
      - uses: docker/build-push-action@v2
        with:
          push: false
          context: build/docker
          tags: ghcr.io/eroshenkoam/allure-testops-utils
      - uses: actions/upload-artifact@v3
        with:
          name: allure-testops-utils
          retention-days: 5
