name: Build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm'
      - run: ./gradlew build
      - run: ./gradlew nativeCompile
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.PACKAGES_USER }}
          password: ${{ secrets.PACKAGES_PASS }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: ghcr.io/eroshenkoam/allure-testops-utils:native
