name: Release Publish

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm'
      - run: ./gradlew build
      - run: ./gradlew nativeCompile
      - run: ./gradlew prepareDockerfile
      - run: echo "PROJECT_VERSION=${GITHUB_REF:10}" >> $GITHUB_ENV
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.PACKAGES_USER }}
          password: ${{ secrets.PACKAGES_PASS }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          context: build/docker
          tags: |
            ghcr.io/eroshenkoam/allure-testops-utils:${{ env.PROJECT_VERSION }}
            ghcr.io/eroshenkoam/allure-testops-utils:latest
