name: Release Publish

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm'
      - run: ./gradlew build
      - run: ./gradlew nativeCompile
      - uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/native/nativeCompile/allure-testops-utils
          asset_name: allure-testops-utils
          asset_content_type: application/octet-stream
      - run: echo "PROJECT_VERSION=${GITHUB_REF:10}" >> $GITHUB_ENV
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.PACKAGES_USER }}
          password: ${{ secrets.PACKAGES_PASS }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/eroshenkoam/allure-testops-utils:${{ env.PROJECT_VERSION }}
            ghcr.io/eroshenkoam/allure-testops-utils:latest
